name: Build Android AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: |
          cd react-native-app
          npm install

      - name: Build AAB (con ruta 100 % segura)
        run: |
          cd react-native-app
          cd Android
          pwd
          ls -la gradlew
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: MultiMarket-Pro.aab
          path: react-native-app/Android/app/build/outputs/bundle/release/app-release.aab
